Form-348/legal_text_regulation
bratislava/konto.bratislava.sk pull request #19
Opened 2023-03-16 17:09 UTC by ValeriiMedvezhonkov

fix wording

2023-03-17 09:18 UTC, mpinter requested changes
while at this - this does not seem right at certain screen sizes:

<img width="943" alt="Screenshot 2023-03-17 at 09 57 28" src="https://user-images.githubusercontent.com/2327312/225859032-506992b5-6b2a-4836-ba2d-ee5ff95d88f1.png">

this whole styling is a bit cumbersome but I understand why it ended up like it so .. why it would be nice to rewrite let's not waste time here, just fix the above styling please.

Honeslty, if the issue is that there are to be the newlines in mobile version and no newlines in desktop, let's push back on this in design channel if it chan significantly simplify this code. I'll do that and you can try to use less divs and styling in this meanwhile 🙂 

Finally, if you could also get rid of the `\n\n` for new lines let's do that as well.

2023-03-20 09:54 UTC, mpinter requested changes
see slack

2023-03-20 13:50 UTC, ValeriiMedvezhonkov commented
[fix wording](https://github.com/bratislava/konto.bratislava.sk/pull/19/commits/adbee1c219e510a92fd2057ab4e0281a72fa8c79) commit was 'reverted' + fix '\n\n'

2023-03-20 14:53 UTC, mpinter approved these changes

2023-03-20 15:00 UTC, merged