Infrastructure/monorepo setup for nest-forms-backend
bratislava/konto.bratislava.sk pull request #968
Opened 2024-04-29 10:48 UTC by skifahrer

This PR adds mono-repo pipelines support for nest-forms-backend. When are nest-forms-backend ready (ie pull requests merged) then we can move it to root folder.

Also to make whole pipeline working, we need to address update in bratiska-cli which will be adressed in another PR request.

Update 6.5.2024 - newest version of nest-forms-backend is included here

2024-05-22 13:04 UTC, mpinter requested changes
Missing (backend) test runs before forms backend is to be built. - check the actions on forms repo.

---

Other than that:

- I've only scrolled through github actions, no guarantees there :) 🤞 

Notes:
- nest-froms readme needs some love, I'll do this as a followup
- we probably want to move towards a single topolevel docker-compose, but that's also for the future

2024-05-22 15:02 UTC, mpinter approved these changes

2024-05-22 16:53 UTC, mpinter commented on nest-forms-backend/.nvmrc
yes, I know it's been there, just thought this migration is a good point at which to remove it

thanks :+1:

2024-05-23 09:07 UTC, vidriduch approved these changes
In general this will most likely work and can be merged. Therefore I'm approving it as I know we are in a bit of a hurry.
**But**, I think this can be simplified with just few changes

2024-05-23 09:07 UTC, vidriduch commented on nest-forms-backend/LICENSE
> +SOFTWARE.
So I'm know this might be out-of-scope. But can we switch to EUPL-1.2. It is a simple change and we don't need to do it separately.

2024-05-23 09:07 UTC, vidriduch commented on .github/workflows/build-conditions-konto.yml
> +          echo "condition=true" >> $GITHUB_OUTPUT
Isn't this just relabeling of `needs.changes.outputs.nest-forms-backend` to `needs.conditions.output.nest-forms-backend.condition`. Can't we drop this step and just use the output of `changes`? 

Same goes for all other steps in this job.

2024-05-23 12:25 UTC, merged